# Generated by Django 3.0.4 on 2020-03-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
