# Generated by Django 3.0.3 on 2020-03-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='address_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
