# Generated by Django 3.0.3 on 2020-03-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20200328_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
