# Generated by Django 3.0.3 on 2020-03-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20200330_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='timestamp_for_id',
            field=models.IntegerField(default=0),
        ),
    ]
