# Generated by Django 3.0.3 on 2020-03-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_request_timestamp_for_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='timestamp_for_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
