# Generated by Django 3.0.3 on 2020-04-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_code',
            field=models.CharField(default='+91', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='9876543210', max_length=10),
        ),
    ]
